### PR TITLE
What is a Nonlinear Solver? And How to easily build Newer Ones

### LINKED ISSUE #62: Can not iterate solver before solving
When attempting to iterate a solver that has not been solved, the user is told that there is no method matching `iterate` for the solver. Same goes for `getindex`:
```
julia> using NonlinearSolve

julia> f(u, p) = u .* u .- 2.0
f (generic function with 1 method)

julia> u0 = (1.0, 2.0) # brackets
(1.0, 2.0)

julia> probB = NonlinearProblem(f, u0)
NonlinearProblem with uType Tuple{Float64, Float64}. In-place: false
u0: (1.0, 2.0)

julia> solver = init(probB, Falsi()) # Can iterate the solver object
NonlinearSolve.BracketingImmutableSolver{NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Falsi, Float64, Float64, SciMLBase.NullParameters, Nothing, NonlinearProblem{Tuple{Float64, Float64}, false, SciMLBase.NullParameters, NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}}(1, NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}(f, LinearAlgebra.UniformScaling{Bool}(true), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, SciMLBase.DEFAULT_OBSERVED_NO_TIME, nothing), Falsi(), 1.0, 2.0, -1.0, 2.0, SciMLBase.NullParameters(), false, 1000, NonlinearSolve.DEFAULT, nothing, false, NonlinearProblem{Tuple{Float64, Float64}, false, SciMLBase.NullParameters, NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}(NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}(f, LinearAlgebra.UniformScaling{Bool}(true), nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, nothing, SciMLBase.DEFAULT_OBSERVED_NO_TIME, nothing), (1.0, 2.0), SciMLBase.NullParameters(), Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}()))

julia> solver[1]
ERROR: MethodError: no method matching getindex(::NonlinearSolve.BracketingImmutableSolver{NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Falsi, Float64, Float64, SciMLBase.NullParameters, Nothing, NonlinearProblem{Tuple{Float64, Float64}, false, SciMLBase.NullParameters, NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}}, ::Int64)
Stacktrace:
 [1] top-level scope
   @ REPL[6]:1

julia> for s in solver
           @show s
       end
ERROR: MethodError: no method matching iterate(::NonlinearSolve.BracketingImmutableSolver{NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Falsi, Float64, Float64, SciMLBase.NullParameters, Nothing, NonlinearProblem{Tuple{Float64, Float64}, false, SciMLBase.NullParameters, NonlinearFunction{false, typeof(f), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED_NO_TIME), Nothing}, Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}})
Closest candidates are:
  iterate(::Union{LinRange, StepRangeLen}) at C:\Users\Dennis Bal\.julia\juliaup\julia-1.7.1+0~x64\share\julia\base\range.jl:826
  iterate(::Union{LinRange, StepRangeLen}, ::Integer) at C:\Users\Dennis Bal\.julia\juliaup\julia-1.7.1+0~x64\share\julia\base\range.jl:826
  iterate(::T) where T<:Union{Base.KeySet{<:Any, <:Dict}, Base.ValueIterator{<:Dict}} at C:\Users\Dennis Bal\.julia\juliaup\julia-1.7.1+0~x64\share\julia\base\dict.jl:695
  ...
Stacktrace:
 [1] top-level scope
   @ .\REPL[7]:1

julia> solver = solve!(solver)
u: 1.414213562373095

julia> solver[1]
1.414213562373095

julia> for s in solver
           @show s
       end
s = 1.414213562373095
```

However, should the unsolved solver not be an empty collection?

This is especially confusing due to the documentation, which says that you can iterate the solver in the line before it is solved. From http://nonlinearsolve.sciml.ai/dev/tutorials/iterator_interface/ :
```
f(u, p) = u .* u .- 2.0
u0 = (1.0, 2.0) # brackets
probB = NonlinearProblem(f, u0)
solver = init(probB, Falsi()) # Can iterate the solver object
solver = solve!(solver)
```

### LINKED ISSUE #312: Normal Form Linear Solve in Trust Region Methods
Currently we cannot use Normal Form equations in TR. This can be added similar to how Gauss Newton and Levenberg work. Allows us to use Iterative Solvers like GMRES.

In the long run, we want to support LSLQ and such solvers but that requires a minor rewrite of JacVec and VecJac to provide the correct adjoint operators

### PR DESCRIPTION
**Pull request by avik-pal**
## Goals

- [x] Fully Functional Iterator Interface
- [x] Composable Internals. https://github.com/SciML/NonlinearSolve.jl/issues/330 and https://github.com/SciML/NonlinearSolve.jl/issues/216 got me thinking that our level of abstraction before was way off. All our algorithms are essentially the same (okay maybe except the spectral one, but even that can be made composable and we get a bunch of those methods for free) but we keep copying the code around
- [ ] ~Dispatch system with safety to disable NLLS with NewtonRaphson (and similarly for others). Currently it will work which is not the worst thing, but disabling this is a safer option IMO~
- [x] Actually functional `reinit` interface

## How close is this to being ready?

Once tests pass and downstream PRs are merged we should be good to go. I will follow this PR up with:

1. SingleFactorize<....> which can use the iterator interface and `recompute_jacobian` to Jacobian only when needed.
2. Multi-Step Methods
3. Default change to PolyesterForwardDiff similar to SimpleNonlinearSolve

## Documentation

- [x] Dev Docs

## Target Issues

- [x] Fixes #312
- [x] Setup for #247 
- [x] Setup for #241
- [x] Fixes #62 

## Modular Internals

- [x] Descent
  - [x] Newton -- Automatically handle normal form efficiently
  - [x] Cauchy
  - [x] Dogleg -- Mix Newton and Cauchy
  - [x] Damped Newton -- Yes Levenberg-Marquardt and PseudoTransient can share the same internals
    - [x] Rework a little bit for different schemes
- [x] Globalization: Only one can be activated at a time
  - [x] Line Search
  - [x] Trust Region

### CODE REVIEW

File: src/descent/steepest.jl [hunk 1]
```diff
@@ -0,0 +1,66 @@
+"""
+    SteepestDescent(; linsolve = nothing, precs = DEFAULT_PRECS)
+
+Compute the descent direction as ``δu = -Jᵀfu``.
```
Comment (ChrisRackauckas) [inline src/descent/steepest.jl:4]: why is this steepest?

Comment (avik-pal) [reply src/descent/steepest.jl:4]: That's the gradient of $\frac{1}{2}||f(x)||_2$

**Comment by termi-official** [comment]
I may have a special case here to consider and will write it here instead of as a separate issue due to the title of the PR. If I should transfer this information to an issue instead, I am happy to do it.

When discretizing PDEs we often end up with a nonlinear system of equations + constraints (coming from e.g. Dirichlet boundary conditions). For example in Newton methods we also know how to enforce the constraints efficiently: We can rewrite the linear equation system. In Ferrite.jl a typical Newton-Raphson implementation looks like this:
```julia
dh = ... # Holds info about finite element problem
un = zeros(ndofs(dh))
u = zeros(ndofs(dh))
Δu = zeros(ndofs(dh))
... # define remaining variables
dbcs = ... # Holds Dirichlet boundary condition information 
apply!(un, dbcs) # Apply Dirichlet conditions to solution vector
while true; newton_itr += 1
        # Construct the current guess
        u .= un .+ Δu
        # Compute residual and tangent for current guess
        assemble_global!(K, g, dh, cv, fv, mp, u, ΓN)
        # Apply boundary conditions
        apply_zero!(K, g, dbcs)
        # Compute the residual norm and compare with tolerance
        normg = norm(g)
        if normg < NEWTON_TOL
            break
        elseif newton_itr > NEWTON_MAXITER
            error("Reached maximum Newton iterations, aborting")
        end

        # Compute increment
        ΔΔu =  K \ g

        apply_zero!(ΔΔu, dbcs)
        Δu .-= ΔΔu
    end
```
(see https://ferrite-fem.github.io/Ferrite.jl/dev/tutorials/hyperelasticity/ for full example).

I am confident that other frameworks come with similar mechanisms. Basically the difference to a "normal" Newton-Raphson is the `apply!` before entering the iteration to e.g. set the boundary condition in the solution vector and the 2x `apply_zero!`, first to e.g. eliminate the boundary conditions from the linear system and second to remove numerical inaccurracies in the solver from the increment. If it is not clear: The increment must be zero, because the solution is already enforced to be correct by the first call to `apply!`. For e.g. gradient based solvers we need similar hooks.

With this in mind I would like to ask for considering this and possibly recommendations about how this integration can be accompished from user side when using NonlinearSolve.jl. I am happy to help here and also to answer any questions which might come up.

My first idea here was to provide a custom linear solver. This custom solver just wraps the actual linear solver and adds the apply_zero calls in the `solve` function (and when the linear system is regenerated). However, in this case it is not clear how to introduce the first `apply!` in a clean way before going into the iteration.

**Comment by avik-pal** [comment]
One way might be to provide a `preamble` / `postamble` functions with the input being `cache`. I think that might solve your problem @termi-official? Then you can construct the `GeneralizedFirstOr....` method with `NewtonDescent` to get your `NewtonRaphson`.

The only concern here is that with custom functions, the inputs to the `step!` like `recompute_jacobian` might have to be set as incompatible -- unless we rework how the jacobian or `fu` is stored / cached.

**Comment by termi-official** [comment]
So, if I understand correctly, then the current recommendation would be to define a custom linear solver wrapper, as I proposed, and then dispatch the preamble if the cache has this specific linear solver wrapper. I think this makes sense.

Indeed one thing to consider here is that the Dirichlet condition might be time-dependent themselves and this can possibly invalidate the Jacobian (depending on the reusage strategy). I am not sure how to deal with this one properly.

**Comment by avik-pal** [comment]
> if I understand correctly, then the current recommendation would be to define a custom linear solver wrapper, as I proposed

I meant having the preamble function in the `GeneralizedFirstOrder...` algorithm itself. So you create your newton's method as:

```julia
descent = NewtonDescent(; linsolve, precs)
GeneralizedFirstOrderAlgorithm(; concrete_jac, name = :NewtonRaphson,
    linesearch, descent, jacobian_ad = autodiff, preamble = <....>)
```

**Comment by avik-pal** [comment]
That said I am anyways not adding any new functionality in the PR. Most of what is being added is what was incomplete or inconsistent with docs and such. @termi-official can you open a separate issue for this and link this PR, I will open a follow up PR for that?

**Comment by ChrisRackauckas** [comment]
> I am confident that other frameworks come with similar mechanisms. Basically the difference to a "normal" Newton-Raphson is the apply! before entering the iteration to e.g. set the boundary condition in the solution vector and the 2x apply_zero!, first to e.g. eliminate the boundary conditions from the linear system and second to remove numerical inaccurracies in the solver from the increment. If it is not clear: The increment must be zero, because the solution is already enforced to be correct by the first call to apply!. For e.g. gradient based solvers we need similar hooks.

Those are just nonlinear preconditioners, with pre and post preconditioning.

**Comment by avik-pal** [comment]
Once https://github.com/SciML/DiffEqBase.jl/pull/994 is merged, this would be good to go

**Comment by avik-pal** [comment]
Let's go! Everything is working :tada:

**Comment by avik-pal** [comment]
battery_problem_work_precision
Things that were not working before are also working now

File: docs/src/basics/faq.md [hunk 2]
```diff
@@ -90,3 +91,61 @@ end
...
+```@example type_unstable
+@code_warntype solve(prob, NewtonRaphson(; autodiff = AutoForwardDiff(; chunksize = 2)))
+nothing # hide
+```
+
+And boom! Type stable again. For selecting the chunksize the method is:
+
+ 1. For small inputs `≤ 12` use `chunksize = <length of input>`
+ 2. For larger inputs, use `chunksize = 12`
+
```
Comment (ChrisRackauckas) [inline docs/src/basics/faq.md:149]: Maybe just recommend `ForwardDiff.chunksize`?

Comment (ChrisRackauckas) [reply docs/src/basics/faq.md:149]: Or, since that's not public API, we can just make `NonlinearSolve.chunksize` which just calls the ForwardDiff one and is tested so if it moves we just keep this stable.

File: docs/src/basics/solve.md [hunk 3]
```diff
@@ -8,14 +8,19 @@ solve(prob::SciMLBase.NonlinearProblem, args...; kwargs...)
...
 
   - `maxiters::Int`: The maximum number of iterations to perform. Defaults to `1000`.
-  - `abstol::Number`: The absolute tolerance. Defaults to `real(oneunit(T)) * (eps(real(one(T))))^(4 // 5)`.
-  - `reltol::Number`: The relative tolerance. Defaults to `real(oneunit(T)) * (eps(real(one(T))))^(4 // 5)`.
+  - `maxtime`: The maximum time for solving the nonlinear system of equations. Defaults to
+    `nothing` which means no time limit. Note that setting a time limit does have a small
+    overhead.
+  - `abstol::Number`: The absolute tolerance. Defaults to
+    `real(oneunit(T)) * (eps(real(one(T))))^(4 // 5)`.
+  - `reltol::Number`: The relative tolerance. Defaults to
```
Comment (ChrisRackauckas) [inline docs/src/basics/solve.md:22]: These can be vectors matching the size as well?

File: docs/src/native/simplenonlinearsolve.md [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+## General Methods
+
+These methods are suited for any general nonlinear root-finding problem, i.e.
+`NonlinearProblem`.
+
+| Solver                               | In-place | Out of Place | Non-Allocating (Scalars) | Non-Allocating (`SArray`) |
+|:------------------------------------ |:-------- |:------------ |:------------------------ |:------------------------- |
+| [`SimpleNewtonRaphson`](@ref)        | ✔️       | ✔️           | ✔️                       | ✔️                        |
+| [`SimpleBroyden`](@ref)              | ✔️       | ✔️           | ✔️                       | ✔️                        |
+| [`SimpleHalley`](@ref)               | ❌        | ✔️           | ✔️                       | ❌                         |
```
Comment (ChrisRackauckas) [inline docs/src/native/simplenonlinearsolve.md:32]:
```suggestion
| [`SimpleHalley`](@ref)               | ❌       | ✔️           | ✔️                       | ❌                         |
```

File: docs/src/native/simplenonlinearsolve.md [hunk 5]
```diff
@@ -0,0 +1,59 @@
...
+## General Methods
+
+These methods are suited for any general nonlinear root-finding problem, i.e.
+`NonlinearProblem`.
+
+| Solver                               | In-place | Out of Place | Non-Allocating (Scalars) | Non-Allocating (`SArray`) |
+|:------------------------------------ |:-------- |:------------ |:------------------------ |:------------------------- |
+| [`SimpleNewtonRaphson`](@ref)        | ✔️       | ✔️           | ✔️                       | ✔️                        |
+| [`SimpleBroyden`](@ref)              | ✔️       | ✔️           | ✔️                       | ✔️                        |
+| [`SimpleHalley`](@ref)               | ❌       | ✔️           | ✔️                       | ❌                         |
```
Comment (ChrisRackauckas) [inline docs/src/native/simplenonlinearsolve.md:32]: ugh why is this one odd 😅

File: docs/src/solvers/nonlinear_system_solvers.md [hunk 6]
```diff
@@ -0,0 +1,163 @@
...
+difficult yet need high performance, and  [`TrustRegion`](@ref) is a bit less performant but
+more stable. If the problem is well-conditioned, [`Klement`](@ref) or [`Broyden`](@ref) may
+be faster, but highly dependent on the eigenvalues of the Jacobian being sufficiently small.
+
+[`NewtonRaphson`](@ref) and [`TrustRegion`](@ref) are designed for for large systems. They
+can make use of sparsity patterns for sparse automatic differentiation and sparse linear
+solving of very large systems. Meanwhile, [`SimpleNewtonRaphson`](@ref) and
+[`SimpleTrustRegion`](@ref) are implementations which are specialized for small equations.
+They are non-allocating on static arrays and thus really well-optimized for small systems,
+thus usually outperforming the other methods when such types are used for `u0`.
```
Comment (ChrisRackauckas) [inline docs/src/solvers/nonlinear_system_solvers.md:34]: Mention GPUs as well? That should probably get a tutorial too. I think I have left a blank tutorial on static compilation for that kind of stuff.

File: docs/src/solvers/nonlinear_system_solvers.md [hunk 7]
```diff
@@ -0,0 +1,163 @@
...
+### SteadyStateDiffEq.jl
+
+SteadyStateDiffEq.jl uses ODE solvers to iteratively approach the steady state. It is a
+very stable method for solving nonlinear systems with stable equilibrium points, though
+often more computationally expensive than direct methods.
+
+  - [`DynamicSS()`](@ref): Uses an ODE solver to find the steady state. Automatically
+    terminates when close to the steady state.
+  - [`SSRootfind()`](@ref): Uses a NonlinearSolve compatible solver to find the steady
+    state.
```
Comment (ChrisRackauckas) [inline docs/src/solvers/nonlinear_system_solvers.md:120]: This is effectively deprecated for just using NonlinearSolve

File: docs/src/solvers/nonlinear_system_solvers.md [hunk 8]
```diff
@@ -0,0 +1,163 @@
...
+Submethod choices for this algorithm include:
+
+  - `:anderson`: Anderson-accelerated fixed-point iteration
+  - `:newton`: Classical Newton method with an optional line search
+  - `:trust_region`: Trust region Newton method (the default choice)
+
+### MINPACK.jl
+
+MINPACK.jl methods are good for medium-sized nonlinear solves. It does not scale due to
+the lack of sparse Jacobian support, though the methods are very robust and stable.
```
Comment (ChrisRackauckas) [inline docs/src/solvers/nonlinear_system_solvers.md:138]: Are they? The algorithms aren't showing that in comparison 😅

File: docs/src/solvers/nonlinear_system_solvers.md [hunk 9]
```diff
@@ -0,0 +1,163 @@
...
+implementations.
+
+  - [`KINSOL()`](@ref): The KINSOL method of the SUNDIALS C library
+
+### SIAMFANLEquations.jl
+
+SIAMFANLEquations.jl is a wrapper for the methods in the SIAMFANLEquations.jl library.
+
+  - [`SIAMFANLEquationsJL()`](@ref): A wrapper for using the methods in
+    [SIAMFANLEquations.jl](https://github.com/ctkelley/SIAMFANLEquations.jl)
```
Comment (ChrisRackauckas) [inline docs/src/solvers/nonlinear_system_solvers.md:163]: Some of the newer wrappers are missing from this list. SpeedMapping.jl, LeastSquaresOptim.jl, FastLevenburgMarquedt, etc.

File: docs/src/solvers/steady_state_solvers.md [hunk 10]
```diff
@@ -0,0 +1,68 @@
...
+
+The SteadyStateDiffEq.jl methods on a [`SteadyStateProblem`](@ref) respect the time
+definition in the nonlinear definition, i.e., `u' = f(u, t)` uses the correct values for
+`t` as the solution evolves. A conversion of a [`SteadyStateProblem`](@ref) to a
+[`NonlinearProblem`](@ref) replaces this with the nonlinear system `u' = f(u, ∞)`, and thus
+the direct [`SteadyStateProblem`](@ref) approach can give different answers (i.e., the
+correct unique fixed point) on ODEs with non-autonomous dynamics.
+
+If you have an unstable equilibrium and you want to solve for the unstable equilibrium,
+then [`DynamicSS`](@ref) might converge to the equilibrium based on the initial condition.
```
Comment (ChrisRackauckas) [inline docs/src/solvers/steady_state_solvers.md:26]:
```suggestion
then [`DynamicSS`](@ref) will not converge to that equilibrium for any initial condition.
```

File: docs/src/tutorials/large_systems.md [hunk 11]
```diff
@@ -137,11 +137,14 @@ Symbolic Sparsity Detection. See the manual entry on
...
 @btime solve(prob_brusselator_2d,
-    NewtonRaphson(; autodiff = AutoSparseForwardDiff(), linsolve = KLUFactorization()));
+    NewtonRaphson(; autodiff = AutoSparseForwardDiff(; chunksize = 32)));
 @btime solve(prob_brusselator_2d,
-    NewtonRaphson(; autodiff = AutoSparseForwardDiff(), linsolve = KrylovJL_GMRES()));
+    NewtonRaphson(; autodiff = AutoSparseForwardDiff(; chunksize = 32),
+        linsolve = KLUFactorization()));
+@btime solve(prob_brusselator_2d,
+    NewtonRaphson(; autodiff = AutoSparseForwardDiff(; chunksize = 32),
+        linsolve = KrylovJL_GMRES()));
```
Comment (ChrisRackauckas) [inline docs/src/tutorials/large_systems.md:147]: That's a huge chunk size. Is it actually more helpful than 7?

File: ext/NonlinearSolveLeastSquaresOptimExt.jl [hunk 12]
```diff
@@ -4,45 +4,49 @@ using NonlinearSolve, SciMLBase
...
 
-function SciMLBase.__init(prob::NonlinearLeastSquaresProblem, alg::LeastSquaresOptimJL,
-        args...; alias_u0 = false, abstol = nothing, show_trace::Val{ShT} = Val(false),
-        trace_level = TraceMinimal(), store_trace::Val{StT} = Val(false), maxiters = 1000,
-        reltol = nothing, kwargs...) where {ShT, StT}
-    iip = SciMLBase.isinplace(prob)
-    u = NonlinearSolve.__maybe_unaliased(prob.u0, alias_u0)
+function SciMLBase.reinit!(cache::LeastSquaresOptimJLCache, args...; kwargs...)
+    error("Reinitialization not supported for LeastSquaresOptimJL.")
+end
```
Comment (ChrisRackauckas) [inline ext/NonlinearSolveLeastSquaresOptimExt.jl:28]: why only this one but not the other extensions?

File: src/abstract_types.jl [hunk 13]
```diff
@@ -0,0 +1,471 @@
...
+### `SciMLBase.init` specification
+
+```julia
+SciMLBase.init(prob::AbstractNonlinearProblem,
+    alg::AbstractNonlinearSolveLineSearchAlgorithm, f::F, fu, u, p, args...;
+    internalnorm::IN = DEFAULT_NORM,
+    kwargs...) where {F, IN} --> AbstractNonlinearSolveLineSearchCache
+```
+"""
+abstract type AbstractNonlinearSolveLineSearchAlgorithm end
```
Comment (ChrisRackauckas) [inline src/abstract_types.jl:124]: Wasn't this moved to LineSearch.jl?

File: src/algorithms/klement.jl [hunk 14]
```diff
@@ -0,0 +1,146 @@
+"""
+    Klement(; max_resets = 100, linsolve = NoLineSearch(), linesearch = nothing,
+        precs = DEFAULT_PRECS, alpha = nothing, init_jacobian::Val = Val(:identity),
+        autodiff = nothing)
+
+An implementation of `Klement` [klement2014using](@citep) with line search, preconditioning
+and customizable linear solves. It is recommended to use [`Broyden`](@ref) for most problems
+over this.
```
Comment (ChrisRackauckas) [inline src/algorithms/klement.jl:8]: Is that still true? Since the fast polyalg defaults here.

File: src/core/generalized_first_order.jl [hunk 15]
```diff
@@ -0,0 +1,279 @@
...
+            u_cache, p, du, J, alg, prob, jac_cache, descent_cache, linesearch_cache,
+            trustregion_cache, 0, 0, maxiters, maxtime, alg.max_shrink_times, timer, 0.0,
+            true, termination_cache, trace, ReturnCode.Default, false)
+    end
+end
+
+function __step!(cache::GeneralizedFirstOrderAlgorithmCache{iip, GB};
+        recompute_jacobian::Union{Nothing, Bool} = nothing, kwargs...) where {iip, GB}
+    @static_timeit cache.timer "jacobian" begin
+        if (recompute_jacobian === nothing || recompute_jacobian) && cache.make_new_jacobian
```
Comment (ChrisRackauckas) [inline src/core/generalized_first_order.jl:204]: So what's the plan on the ODE solver for triggering new Jacobians? I didn't see the high level function that would be involved. I assume it's not just flipping `make_new_jacobian`?

File: src/default.jl [hunk 16]
```diff
@@ -180,38 +182,18 @@ or more precision / more stable linear solver choice is required).
...
-    [LinearSolve.jl documentation](https://docs.sciml.ai/LinearSolve/stable/).
 """
 function RobustMultiNewton(::Type{T} = Float64; concrete_jac = nothing, linsolve = nothing,
         precs = DEFAULT_PRECS, autodiff = nothing) where {T}
     if __is_complex(T)
         # Let's atleast have something here for complex numbers
         algs = (NewtonRaphson(; concrete_jac, linsolve, precs, autodiff),)
     else
-        algs = (TrustRegion(; concrete_jac, linsolve, precs, autodiff),
+        algs = (TrustRegion(; concrete_jac, linsolve, precs),
```
Comment (ChrisRackauckas) [inline src/default.jl:192]: why remove that autodiff here?

File: src/descent/dogleg.jl [hunk 17]
```diff
@@ -0,0 +1,136 @@
...
+    normal_form = prob isa NonlinearLeastSquaresProblem &&
+                  __needs_square_A(alg.newton_descent.linsolve, u)
+    JᵀJ_cache = !normal_form ? J * _vec(δu) : nothing  # TODO: Rename
+
+    return DoglegCache{INV, normal_form}(δu, δus, newton_cache, cauchy_cache, internalnorm,
+        JᵀJ_cache, δu_cache_1, δu_cache_2, δu_cache_mul)
+end
+
+# If TrustRegion is not specified, then use a Gauss-Newton step
+function SciMLBase.solve!(cache::DoglegCache{INV, NF}, J, fu, u, idx::Val{N} = Val(1);
```
Comment (ChrisRackauckas) [inline src/descent/dogleg.jl:78]: I don't know about putting these all on the main init and solve because they are meant to be internal?

File: src/internal/helpers.jl [hunk 18]
```diff
@@ -0,0 +1,262 @@
...
+        check_reverse_mode = true, kwargs...) where {test_sparse}
+    if check_reverse_mode
+        @warn "$(autodiff)::$(typeof(autodiff)) is not a \
+               `Abstract(Forward/FiniteDifferences)Mode`. Use with caution." maxlog=1
+    end
+    return autodiff
+end
+function get_concrete_forward_ad(autodiff, prob, sp::Val{test_sparse} = True, args...;
+        kwargs...) where {test_sparse}
+    # TODO: Default to PolyesterForwardDiff for non sparse problems
```
Comment (ChrisRackauckas) [inline src/internal/helpers.jl:56]: Make an issue?

File: src/internal/helpers.jl [hunk 19]
```diff
@@ -0,0 +1,262 @@
...
+        kwargs...) where {test_sparse}
+    if check_reverse_mode
+        @warn "$(autodiff)::$(typeof(autodiff)) is not a \
+               `Abstract(Forward/FiniteDifferences)Mode`. Use with caution." maxlog=1
+    end
+    return autodiff
+end
+function get_concrete_reverse_ad(autodiff, prob, sp::Val{test_sparse} = True, args...;
+        kwargs...) where {test_sparse}
+    # TODO: Default to Enzyme / ReverseDiff for inplace problems?
```
Comment (ChrisRackauckas) [inline src/internal/helpers.jl:99]: Make an issue?

File: src/internal/jacobian.jl [hunk 20]
```diff
@@ -0,0 +1,191 @@
...
+
+# Sparsity Detection Choices
+@inline __sparsity_detection_alg(_, _) = NoSparsityDetection()
+@inline function __sparsity_detection_alg(f::NonlinearFunction, ad::AbstractSparseADType)
+    if f.sparsity === nothing
+        if f.jac_prototype === nothing
+            if is_extension_loaded(Val(:Symbolics))
+                return SymbolicsSparsityDetection()
+            else
+                return ApproximateJacobianSparsity()
```
Comment (ChrisRackauckas) [inline src/internal/jacobian.jl:150]: As a default?

**Comment by ChrisRackauckas** [comment]
A bunch of small comments and issues to open, otherwise good to go!

File: src/default.jl (hunk 16 above)
Comment (avik-pal) [reply src/default.jl:192]: Accidental will fix this

File: src/core/generalized_first_order.jl (hunk 15 above)
Comment (avik-pal) [reply src/core/generalized_first_order.jl:204]: There are 2 possibilities:

1. the ODE solver uses the iterator form, and passes in `recompute_jacobian = false` if it wants to prevent a new jacobian construction
2. we have an inbuilt SingleFactorizeNewton which is similar to KINSOL and sets the make_new_jacobian internally.

File: src/algorithms/klement.jl (hunk 14 above)
Comment (avik-pal) [reply src/algorithms/klement.jl:8]: Klement is a very interested solver. If it works it converges faster than Broyden but it works in very limited situations. We can consider removing it from the polyalgorithm.

File: src/abstract_types.jl (hunk 13 above)
Comment (avik-pal) [reply src/abstract_types.jl:124]: Not yet, but that is the eventual plan. We still need to figure out how to decouple the line searches like `RobustNonMonotoneLineSearch` which heavily ties into the cache.

File: docs/src/basics/solve.md (hunk 3 above)
Comment (avik-pal) [reply docs/src/basics/solve.md:22]: No that is not implemented.

File: src/internal/jacobian.jl (hunk 20 above)
Comment (avik-pal) [reply src/internal/jacobian.jl:150]: Symbolics is actually pretty good after a size threshold, and even faster than the approximate version.

File: docs/src/tutorials/large_systems.md (hunk 11 above)
Comment (avik-pal) [reply docs/src/tutorials/large_systems.md:147]: In this case it actually gave a speedup locally till 32 but larger than this made the code slow.

File: src/internal/helpers.jl (hunk 18 above)
Comment (avik-pal) [reply src/internal/helpers.jl:56]: https://github.com/SciML/NonlinearSolve.jl/issues/353

File: src/internal/helpers.jl (hunk 19 above)
Comment (avik-pal) [reply src/internal/helpers.jl:99]: https://github.com/SciML/NonlinearSolve.jl/issues/353

File: docs/src/basics/faq.md (hunk 2 above)
Comment (avik-pal) [reply docs/src/basics/faq.md]: Done, naming it `pickchunksize` similar to what ForwardDiff does

File: docs/src/solvers/nonlinear_system_solvers.md (hunk 6 above)
Comment (avik-pal) [reply docs/src/solvers/nonlinear_system_solvers.md:34]: Mentioned it, I might do a section on GPU compilation for the paper, I will port that over when done.

File: docs/src/solvers/nonlinear_system_solvers.md (hunk 8 above)
Comment (avik-pal) [reply docs/src/solvers/nonlinear_system_solvers.md]: Yeah. not really. Changed the text.

File: docs/src/solvers/nonlinear_system_solvers.md (hunk 9 above)
Comment (avik-pal) [reply docs/src/solvers/nonlinear_system_solvers.md:166]: Linked them from here to avoid repeating the text.

File: docs/src/solvers/steady_state_solvers.md (hunk 10 above)
Comment (avik-pal) [reply docs/src/solvers/steady_state_solvers.md]: Done

File: docs/src/native/simplenonlinearsolve.md (hunk 5 above)
Comment (avik-pal) [reply docs/src/native/simplenonlinearsolve.md:32]: I don't think so, the initial formatting came from my default markdown formatted in vscode.

Comment (avik-pal) [reply docs/src/native/simplenonlinearsolve.md]: actually JuliaFormatter formats it back to the original one before your commit.

File: src/descent/dogleg.jl (hunk 17 above)
Comment (avik-pal) [reply src/descent/dogleg.jl]: makes sense. dispatching on `__internal_init` and `__internal_solve!`

**Comment by avik-pal** [comment]
the dae failure is real https://github.com/SciML/NonlinearSolve.jl/actions/runs/7543078285/job/20533293590?pr=345#step:6:1759. The cache is initialized with a Vector but later it gets a subarray

File: src/internal/jacobian.jl (hunk 20 above)
Comment (ChrisRackauckas) [reply src/internal/jacobian.jl:150]: I mean defaulting to approximate Jacobian sparsity seems a bit odd. Even if it's not AD?

File: src/core/generalized_first_order.jl (hunk 15 above)
Comment (ChrisRackauckas) [reply src/core/generalized_first_order.jl:206]: > the ODE solver uses the iterator form, and passes in recompute_jacobian = false if it wants to prevent a new jacobian construction

Oh I missed that. That works.

File: docs/src/basics/solve.md (hunk 3 above)
Comment (ChrisRackauckas) [reply docs/src/basics/solve.md:22]: We should make an issue on this then. It just needs to use broadcast?

**Review by ChrisRackauckas — APPROVED** [review]
Looks like my comments were addressed. Let's get some issues open on nonlinear preconditioning, Klement in the polyalg, linesearch removal, and non-scalar tolerances.

**Comment by ChrisRackauckas** [comment]
> the dae failure is real https://github.com/SciML/NonlinearSolve.jl/actions/runs/7543078285/job/20533293590?pr=345#step:6:1759. The cache is initialized with a Vector but later it gets a subarray

We should just make the cache via a view too.

**Comment by ChrisRackauckas** [comment]
Make an issue in OrdinaryDiffEq with the DAE one, I can take a look at that later today.
